[package]
name = "rust-os"
version = "0.1.0"
edition = "2024"

[dependencies]
util.path = "./util/"
bitset.path = "./bitset/"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[workspace]
members = [".", "bitset", "user/user", "util"]

[workspace.dependencies]
paste = "1.0"
