[package]
name = "rust-os"
version = "0.1.0"
edition = "2024"

[dependencies]
util.path = "./util/"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[workspace]
members = [".", "./util/", "util"]
